version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "C:/Users/2971392321015/Desktop/Teste2/backend2/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin