openapi: 3.0.0
info:
  title: API de Exemplo
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retorna mensagem de olá
      responses:
        '200':
          description: Resposta de sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Olá, mundo!
